= README
This repository is a tool I use in Ubuntu, It uses a script to complete the initialization action.


// TODO: maybe delete some "font" files

== Neovim
When you first enter nvim, you need to wait for it to finish. If there is an error, you can try Update or reinstall the plugin. After the entire script is completed, enter nvim again and run lazygit to update the plugin better.

[source, shell]
----
# in neovim
Copilot auth

----

// = README
// :experimental:
// :toc: right
// :imagesdir: images
// == Docker
== 安裝

link:./README.adoc[English]

[NOTE]
====
需要相應地轉換以下內容。

* `<README_PATH>` 是 *README.adoc* 檔案的所在目錄。
====

[source, shell]
----
# 安裝 docker 和 nvidia-container-toolkit
cd <this directory>
chmod +x ./install.sh
./install.sh

# 驗證安裝
docker -v
nvidia-container-toolkit -version
----

== 使用方法
// TODO: Add it after Notion is completed.
* [我的 Notion 教學]

== 移除
[source, shell]
----
# 移除 docker 和 nvidia-container-toolkit
cd <this directory>
chmod +x ./remove.sh
./remove.sh

# 驗證移除
docker -v
nvidia-container-toolkit -version
# docker, nvidia-container-toolkit 命令未找到。
----

== 參考資料
* https://www.docker.com/[Docker 官方網站]
* https://docs.docker.com/engine/install/ubuntu/[在 Ubuntu 上安裝 Docker 引擎]
* https://docs.docker.com/engine/install/linux-postinstall/[Linux 後安裝步驟]
* https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html[NVIDIA 容器工具包]

== samll tools
---
link:./README_ch.adoc[繁體中文]

== Install
[NOTE]
====
The following content needs to be converted accordingly.

* `<README_PATH>` is the directory where this *README.adoc* file is located.
* `<FILE_PATH>` is the path of the file you want to view.
* `<URL>` is the URL of the file you want to download.
* `<WORKSPACE_PATH>` is the directory where you want to create a new repository.
* `<JSON_PATH>` is the path of the JSON file you want to view.
* `<IP>` is the IP address of the target.
* `<MASK>` is the subnet mask of the target.
* `[FOLDER_PATH]` is the path of the folder you want to navigate to. (optional)
* `<COMMAND>` is the command you want to know more about.
* `<NUM>` is the number of levels you want to display. (optional)
====

[source, shell]
----
cd <README_PATH>
chmod +x ./install.sh
./install.sh
----

== Usage
.Monitor tools
[source, shell]
----
# bashtop
bashtop

# bpytop
bpytop

# bmon
bmon

# htop
htop

# nmon
nmon

# powertop
sudo powertop

# iftop
sudo iftop

# iotop
sudo iotop
----

.Other tools
[source, shell]
----
# apt-file
sudo apt-file search <COMMAND>

# bat
bat <FILE_PATH>

# fish
fish
## if you want to use fish ssh-agent,
## ssh key file name must be id_ed25519 (default name),
## or modify config.fish youself.

# git
cd <WORKSPACE_PATH>
git init
## local（once per repository）
git config --local init.defaultBranch "main"
git config --local user.name "your name"
git config --local user.email "email@example.com"
## optional
git config --local core.editor "editor"

## global（once per computer）
git config --global init.defaultBranch "main"
git config --global user.name "your name"
git config --global user.email "email@example.com"
## optional
git config --global core.editor "editor"

# jq
cat <JSON_PATH> | jq '.'

# neofetch
neofetch

# net-tools
ifconfig

# nmap
nmap <IP>/<MASK>

# powerstat
sudo powerstat

# ranger
ranger [FOLDER_PATH]

# silversearcher-ag
ag replace grep

# tig
tig [--all]
tig status

# tldr
tldr <COMMAND>

# tree
tree [FOLDER_PATH]
tree [-C] [-L <NUM>] [FOLDER_PATH]

# wget
wget -O <FILE_PATH> <URL>

# zoxide
z <FOLDER_PATH>
----

.ssh
[source, shell]
----
# 修改 config
<EDITOR> ~/.ssh/config
----

== Remove
[source, shell]
----
cd <README_PATH>
chmod +x ./remove.sh
./remove.sh
----

== Interesting
* https://github.com/romner-set/btop-gpu[btop-gpu Github (*not install*, but can see the GPU, awesome!)]

// TODO: segmentation all tool
