#!/usr/bin/env bats
# test/unit/script/gen_module_index_spec.bats
#
# Tests for `script/gen-module-index.sh` (issue #47, PRD M14): the
# doc/module/INDEX.md generator that extracts NAME / CATEGORY / TAGS /
# DESCRIPTION[en] from module metadata.
#
# Strategy: point INIT_UBUNTU_MODULE_DIR at a fixture dir with known
# *.module.sh files and assert on the emitted Markdown. Two extra checks
# run against the real module/ tree: full coverage (every module has a
# row) and freshness (committed INDEX.md matches a regeneration —
# the issue #47 determinism AC, enforced in CI).

load "${BATS_TEST_DIRNAME}/../../helper/common"

setup() {
    setup_test_env
    SCRIPT="${REPO_ROOT}/script/gen-module-index.sh"
    FIXTURE_MODULE_DIR="${BATS_TEST_TMPDIR}/module"
    mkdir -p "${FIXTURE_MODULE_DIR}"
}

teardown() {
    teardown_test_env
}

# _make_module <name> <category> <tags-words> <description-en>
_make_module() {
    cat > "${FIXTURE_MODULE_DIR}/$1.module.sh" <<EOF
NAME="$1"
CATEGORY="$2"
TAGS=($3)
declare -gA DESCRIPTION=(
    [en]="$4"
    [zh-TW]="(zh) $4"
)
EOF
}

@test "emits AUTO-GENERATED header with regeneration command" {
    _make_module alpha optional "cli" "Alpha tool"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    assert_output --partial "AUTO-GENERATED by script/gen-module-index.sh"
    assert_output --partial "DO NOT EDIT BY HAND"
    assert_output --partial "./script/gen-module-index.sh > doc/module/INDEX.md"
}

@test "emits one table row per module with all metadata columns" {
    _make_module alpha optional "cli extras" "Alpha tool for testing"
    _make_module beta-tool recommended "shell" "Beta shell helper"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    assert_line "| [alpha](../../module/alpha.module.sh) | optional | cli extras | Alpha tool for testing |"
    assert_line "| [beta-tool](../../module/beta-tool.module.sh) | recommended | shell | Beta shell helper |"
}

@test "module count in the prose matches the fixture set" {
    _make_module alpha optional "cli" "Alpha"
    _make_module beta optional "cli" "Beta"
    _make_module gamma base "core" "Gamma"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    assert_output --partial "3 modules."
}

@test "escapes pipe characters in description cells" {
    _make_module alpha optional "cli" "uses a | pipe in text"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    assert_output --partial 'uses a \| pipe in text'
}

@test "ignores non-module files in the module dir" {
    _make_module alpha optional "cli" "Alpha tool"
    touch "${FIXTURE_MODULE_DIR}/setup_legacy.sh"
    touch "${FIXTURE_MODULE_DIR}/helper.bash"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    refute_output --partial "setup_legacy"
    refute_output --partial "helper.bash"
}

@test "fails loudly when a module yields no NAME" {
    printf 'CATEGORY="optional"\n' > "${FIXTURE_MODULE_DIR}/broken.module.sh"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_failure
    assert_output --partial "broken.module.sh"
    assert_output --partial "did not yield a NAME"
}

@test "regeneration is deterministic (two runs byte-identical)" {
    _make_module zeta optional "cli" "Zeta"
    _make_module alpha base "core" "Alpha"
    _make_module mid recommended "shell" "Mid"
    local _out1="${BATS_TEST_TMPDIR}/out1.md"
    local _out2="${BATS_TEST_TMPDIR}/out2.md"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" "${SCRIPT}" > "${_out1}"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" "${SCRIPT}" > "${_out2}"
    run diff "${_out1}" "${_out2}"
    assert_success
}

@test "row order is deterministic (sorted by file name)" {
    _make_module zeta optional "cli" "Zeta"
    _make_module alpha base "core" "Alpha"
    _make_module mid recommended "shell" "Mid"
    INIT_UBUNTU_MODULE_DIR="${FIXTURE_MODULE_DIR}" run "${SCRIPT}"
    assert_success
    local _names
    _names="$(printf '%s\n' "${output}" | grep -o '^| \[[a-z-]*\]' )"
    [ "${_names}" = "$(printf '| [alpha]\n| [mid]\n| [zeta]')" ]
}

@test "real module dir: every module/*.module.sh has a row" {
    run "${SCRIPT}"
    assert_success
    local _f _name
    for _f in "${MODULE_DIR}"/*.module.sh; do
        _name="$(basename "${_f}" .module.sh)"
        assert_output --partial "](../../module/${_name}.module.sh)"
    done
}

@test "committed doc/module/INDEX.md is up to date" {
    local _regen="${BATS_TEST_TMPDIR}/regen.md"
    "${SCRIPT}" > "${_regen}"
    run diff "${REPO_ROOT}/doc/module/INDEX.md" "${_regen}"
    assert_success
}
