#!/usr/bin/env bash
# lib/config.sh — read / write the user config.ini
#
# Per PRD §10.3 (User config) and the U1 inline-edit ban: callers MUST
# go through `setup_ubuntu config set/get/unset/show`, NEVER hand-edit
# config.ini. The file carries a generated-file warning header to make
# this obvious.
#
# Public API:
#   config_get_path
#   config_init
#   config_get <section.key>
#   config_set <section.key> <value>
#   config_unset <section.key>
#   config_show [--json]
#
# Implementation: pure bash + awk for INI; jq only for --json output.
# No quoted values, nested sections, multi-line values, or inline comments.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    printf "Warn: %s is a library, not a executable script.\n" "${BASH_SOURCE[0]##*/}"
    return 0 2>/dev/null
fi

readonly CONFIG_HEADER_LINES=(
"# ==========================================================================="
"# THIS FILE IS AUTO-GENERATED BY setup_ubuntu. DO NOT EDIT BY HAND."
"# Edit via:  setup_ubuntu config set <section.key> <value>"
"#            setup_ubuntu config unset <section.key>"
"# Manual edits will be preserved on a best-effort basis but may be"
"# overwritten by future schema migrations without notice."
"# ==========================================================================="
)

# ── Path resolution ─────────────────────────────────────────────────────────

config_get_path() {
    local _dir="${INIT_UBUNTU_CONFIG_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/init_ubuntu}"
    printf '%s/config.ini' "${_dir}"
}

# ── Header writer ───────────────────────────────────────────────────────────

_config_write_header() {
    local _path="$1"
    : > "${_path}"
    local _line
    for _line in "${CONFIG_HEADER_LINES[@]}"; do
        printf '%s\n' "${_line}" >> "${_path}"
    done
}

# ── init ────────────────────────────────────────────────────────────────────

config_init() {
    local _path; _path="$(config_get_path)"
    local _dir; _dir="$(dirname "${_path}")"
    mkdir -p "${_dir}"
    if [[ ! -f "${_path}" ]]; then
        _config_write_header "${_path}"
    fi
}

# ── INI parser (awk) ────────────────────────────────────────────────────────

_config_dump_tsv() {
    local _path="$1"
    [[ -f "${_path}" ]] || return 0
    awk '
        BEGIN { sec="" }
        /^[[:space:]]*#/  { next }
        /^[[:space:]]*$/  { next }
        /^[[:space:]]*\[.+\][[:space:]]*$/ {
            s = $0
            gsub(/^[[:space:]]*\[/, "", s)
            gsub(/\][[:space:]]*$/, "", s)
            sec = s
            next
        }
        /=/ {
            key = $0
            val = $0
            sub(/=.*/, "", key)
            sub(/^[^=]*=/, "", val)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
            if (key != "" && sec != "") print sec "\t" key "\t" val
        }
    ' "${_path}"
}

_config_split_key() {
    local _dotted="$1"
    local -n _sec_ref="$2"
    local -n _key_ref="$3"
    _sec_ref="${_dotted%%.*}"
    _key_ref="${_dotted#*.}"
    if [[ "${_sec_ref}" == "${_dotted}" || -z "${_key_ref}" ]]; then
        return 1
    fi
}

# ── get ─────────────────────────────────────────────────────────────────────

config_get() {
    local _dotted="${1:?config_get needs <section.key>}"
    local _sec _key
    _config_split_key "${_dotted}" _sec _key || {
        printf "[config] ERROR: '%s' must be section.key form\n" "${_dotted}" >&2
        return 2
    }
    local _path; _path="$(config_get_path)"
    [[ -f "${_path}" ]] || return 0

    _config_dump_tsv "${_path}" | awk -F'\t' \
        -v sec="${_sec}" -v key="${_key}" '
        $1 == sec && $2 == key { print $3; exit }
    '
}

# ── set ─────────────────────────────────────────────────────────────────────

_config_rebuild() {
    local _path="$1"
    local _tmp_tsv="$2"

    local _new; _new="$(mktemp "${_path}.XXXXXX")"
    _config_write_header "${_new}"

    sort -t $'\t' -k1,1 -k2,2 "${_tmp_tsv}" \
        | awk -F'\t' '
            BEGIN { cur="" }
            {
                if ($1 != cur) {
                    if (cur != "") print ""
                    print "[" $1 "]"
                    cur = $1
                }
                print $2 " = " $3
            }
        ' >> "${_new}"

    mv "${_new}" "${_path}"
}

config_set() {
    local _dotted="${1:?config_set needs <section.key>}"
    if [[ "$#" -lt 2 ]]; then
        printf "[config] ERROR: config_set needs <section.key> <value>\n" >&2
        return 2
    fi
    local _value="$2"
    local _sec _key
    _config_split_key "${_dotted}" _sec _key || {
        printf "[config] ERROR: '%s' must be section.key form\n" "${_dotted}" >&2
        return 2
    }

    config_init
    local _path; _path="$(config_get_path)"

    local _tsv; _tsv="$(mktemp)"
    _config_dump_tsv "${_path}" \
        | awk -F'\t' -v sec="${_sec}" -v key="${_key}" '
            !($1 == sec && $2 == key) { print }
        ' > "${_tsv}"
    printf '%s\t%s\t%s\n' "${_sec}" "${_key}" "${_value}" >> "${_tsv}"

    _config_rebuild "${_path}" "${_tsv}"
    rm -f "${_tsv}"
}

# ── unset ───────────────────────────────────────────────────────────────────

config_unset() {
    local _dotted="${1:?config_unset needs <section.key>}"
    local _sec _key
    _config_split_key "${_dotted}" _sec _key || {
        printf "[config] ERROR: '%s' must be section.key form\n" "${_dotted}" >&2
        return 2
    }

    local _path; _path="$(config_get_path)"
    [[ -f "${_path}" ]] || return 0

    local _tsv; _tsv="$(mktemp)"
    _config_dump_tsv "${_path}" \
        | awk -F'\t' -v sec="${_sec}" -v key="${_key}" '
            !($1 == sec && $2 == key) { print }
        ' > "${_tsv}"

    _config_rebuild "${_path}" "${_tsv}"
    rm -f "${_tsv}"
}

# ── show ────────────────────────────────────────────────────────────────────

config_show() {
    local _json="false"
    if [[ "${1:-}" == "--json" ]]; then
        _json="true"
    fi
    local _path; _path="$(config_get_path)"
    if [[ ! -f "${_path}" ]]; then
        if [[ "${_json}" == "true" ]]; then printf '{}\n'; fi
        return 0
    fi

    if [[ "${_json}" == "false" ]]; then
        cat "${_path}"
        return 0
    fi

    if ! command -v jq >/dev/null 2>&1; then
        printf "[config] ERROR: --json requires jq (in apt-essentials)\n" >&2
        return 1
    fi

    # Build {section:{key:value}} via jq from the TSV stream.
    _config_dump_tsv "${_path}" \
        | jq -R -s '
            split("\n")
            | map(select(length > 0))
            | map(split("\t"))
            | group_by(.[0])
            | map({ (.[0][0]): (map({(.[1]): .[2]}) | add) })
            | add // {}
        '
}
