#!/usr/bin/env bash
# gen-module-index.sh — Generate doc/module/INDEX.md from module metadata
#
# Sources every module/*.module.sh in a throwaway sub-shell (same isolation
# pattern as lib/registry.sh) and emits a Markdown table built from the
# metadata block (doc/module-spec.md §3): NAME / CATEGORY / TAGS /
# DESCRIPTION[en].
#
# Output is deterministic (issue #47 AC): rows follow bash glob order under
# LC_ALL=C (i.e. sorted by file name), and the file contains no timestamps —
# re-running the generator on an unchanged module/ tree is byte-identical.
#
# Per-module pages (doc/module/<name>.md) are a later milestone; this
# generator currently emits the INDEX only.
#
# Env:
#   INIT_UBUNTU_MODULE_DIR  Override the module dir scanned for *.module.sh
#                           (tests point this at a fixture dir).
#
# Usage:
#   ./script/gen-module-index.sh > doc/module/INDEX.md

set -euo pipefail

# Deterministic glob collation regardless of host locale.
export LC_ALL=C

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
readonly SCRIPT_DIR
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd -P)"
readonly REPO_ROOT

MODULE_DIR="${INIT_UBUNTU_MODULE_DIR:-${REPO_ROOT}/module}"

# ── Metadata extraction (one module per sub-shell) ──────────────────────────
#
# The module is source'd, not executed: BASH_SOURCE[0] != $0, so the
# dual-mode header sets MODULE_STANDALONE=false and skips lib bootstrap and
# the standalone footer. Archetype macro calls are undefined in that bare
# shell — `set +e` + stderr suppression lets the metadata assignments
# survive them (identical trade-off to lib/registry.sh `_registry_parse_one`).
_gen_parse_one() {
    local _file="${1:?_gen_parse_one needs <file>}"

    bash --noprofile --norc -c '
        set +e
        source "$1" 2>/dev/null || exit 2

        printf "NAME=%s\n" "${NAME:-}"
        printf "CATEGORY=%s\n" "${CATEGORY:-}"
        printf "TAGS=%s\n" "${TAGS[*]:-}"
        printf "DESC=%s\n" "${DESCRIPTION[en]:-}"
    ' _gen_parse_one "${_file}"
}

# Escape Markdown table delimiters in a cell value.
_gen_md_escape() {
    local _s="${1:-}"
    printf '%s' "${_s//|/\\|}"
}

# ── Collect rows ─────────────────────────────────────────────────────────────

declare -a _rows=()
_count=0

for _file in "${MODULE_DIR}"/*.module.sh; do
    [[ -e "${_file}" ]] || continue  # empty dir: nullglob not set

    _name="" _category="" _tags="" _desc=""
    while IFS= read -r _line; do
        _key="${_line%%=*}"
        _val="${_line#*=}"
        case "${_key}" in
            NAME)     _name="${_val}"     ;;
            CATEGORY) _category="${_val}" ;;
            TAGS)     _tags="${_val}"     ;;
            DESC)     _desc="${_val}"     ;;
        esac
    done < <(_gen_parse_one "${_file}")

    if [[ -z "${_name}" ]]; then
        printf "[gen-module-index] ERROR: %s did not yield a NAME (parse failure or missing metadata)\n" \
            "${_file##*/}" >&2
        exit 1
    fi

    _rows+=("$(printf '| [%s](../../module/%s) | %s | %s | %s |' \
        "$(_gen_md_escape "${_name}")" \
        "${_file##*/}" \
        "$(_gen_md_escape "${_category}")" \
        "$(_gen_md_escape "${_tags}")" \
        "$(_gen_md_escape "${_desc}")")")
    _count=$((_count + 1))
done

# ── Emit ─────────────────────────────────────────────────────────────────────

cat <<'EOF'
<!-- AUTO-GENERATED by script/gen-module-index.sh — DO NOT EDIT BY HAND.
     Regenerate with:  ./script/gen-module-index.sh > doc/module/INDEX.md  -->

# Module Index

EOF

printf '%d modules. Columns come from each module'"'"'s metadata block\n' "${_count}"
cat <<'EOF'
(`NAME` / `CATEGORY` / `TAGS` / `DESCRIPTION[en]`, doc/module-spec.md §3).
Per-module pages will land in a later milestone; until then each name links
to the module source.

| Module | Category | Tags | Description |
|---|---|---|---|
EOF

for _row in "${_rows[@]}"; do
    printf '%s\n' "${_row}"
done
