// Copyright 2023 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT


#ifdef JOYSTICK_ENABLE

  #undef ANALOG_JOYSTICK_Y_AXIS_PIN
  #define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
  #undef ANALOG_JOYSTICK_X_AXIS_PIN
  #define ANALOG_JOYSTICK_X_AXIS_PIN GP26
  #undef POINTING_DEVICE_INVERT_Y
  #define POINTING_DEVICE_INVERT_Y
  #undef POINTING_DEVICE_INVERT_X
  // #undef ANALOG_JOYSTICK_SPEED_REGULATOR
  // #define ANALOG_JOYSTICK_SPEED_REGULATOR 10

#endif // JOYSTICK_ENABLE


#ifdef RGB_MATRIX_ENABLE

  #undef RGB_MATRIX_TIMEOUT
  #define RGB_MATRIX_TIMEOUT 180000
  #undef RGB_MATRIX_STARTUP_SPD
  #define RGB_MATRIX_STARTUP_SPD 60

#endif // RGB_MATRIX_ENABLE


#ifdef COMBO_ENABLE

  #undef COMBO_TERM
  #define COMBO_TERM 100

#endif // COMBO_ENABLE
