#!/usr/bin/env bats
# tests/unit/config_spec.bats — lib/config.sh

load "${BATS_TEST_DIRNAME}/../helpers/common"

setup() {
    setup_test_env
    export LOG_LEVEL=INFO
    export LOG_COLOR=false
}

teardown() {
    teardown_test_env
}

_load_config() {
    # shellcheck disable=SC1091
    source "${LIB_DIR}/config.sh"
}

# ── path + init ─────────────────────────────────────────────────────────────

@test "config_get_path returns path under INIT_UBUNTU_CONFIG_DIR" {
    _load_config
    local _p; _p="$(config_get_path)"
    [[ "${_p}" == "${INIT_UBUNTU_CONFIG_DIR}/config.ini" ]]
}

@test "config_init creates config.ini with the auto-generated header" {
    _load_config
    config_init
    local _p; _p="$(config_get_path)"
    [[ -f "${_p}" ]]
    run head -1 "${_p}"
    assert_output --partial "==="
    run grep -c "AUTO-GENERATED BY setup_ubuntu" "${_p}"
    assert_output "1"
}

@test "config_init is idempotent" {
    _load_config
    config_init
    local _p; _p="$(config_get_path)"
    printf "[ui]\nlang = en\n" >> "${_p}"
    config_init
    grep -q "^lang = en" "${_p}"
}

# ── set + get ──────────────────────────────────────────────────────────────

@test "config_set writes a [section] / key = value pair" {
    _load_config
    config_set ui.lang zh-TW
    run config_get ui.lang
    assert_success
    assert_output "zh-TW"
}

@test "config_set updates an existing key (no duplicate lines)" {
    _load_config
    config_set ui.lang zh-TW
    config_set ui.lang en
    run config_get ui.lang
    assert_success
    assert_output "en"
    local _p; _p="$(config_get_path)"
    run grep -c "^lang = " "${_p}"
    assert_output "1"
}

@test "config_set on a new section creates the section header" {
    _load_config
    config_set platform.override server
    local _p; _p="$(config_get_path)"
    grep -q "^\[platform\]$" "${_p}"
    grep -q "^override = server$" "${_p}"
}

@test "config_set multiple sections keeps them sorted" {
    _load_config
    config_set zoo.x 1
    config_set alpha.y 2
    config_set middle.z 3
    local _p; _p="$(config_get_path)"
    local _sections
    _sections="$(grep -E '^\[' "${_p}" | tr -d '[]')"
    [[ "$(echo "${_sections}" | head -1)" == "alpha" ]]
    [[ "$(echo "${_sections}" | sed -n '2p')" == "middle" ]]
    [[ "$(echo "${_sections}" | tail -1)" == "zoo" ]]
}

@test "config_get on missing key returns empty + success" {
    _load_config
    config_init
    run config_get ui.lang
    assert_success
    assert_output ""
}

@test "config_get rejects malformed key (no dot)" {
    _load_config
    run config_get plainkey
    assert_failure 2
    assert_output --partial "section.key"
}

# ── unset ──────────────────────────────────────────────────────────────────

@test "config_unset removes the key" {
    _load_config
    config_set ui.lang en
    config_set ui.color auto
    config_unset ui.lang
    run config_get ui.lang
    assert_success
    assert_output ""
    run config_get ui.color
    assert_output "auto"
}

@test "config_unset is idempotent on missing key" {
    _load_config
    config_init
    run config_unset ui.bogus
    assert_success
}

# ── show ────────────────────────────────────────────────────────────────────

@test "config_show prints the raw ini" {
    _load_config
    config_set ui.lang zh-TW
    run config_show
    assert_success
    assert_output --partial "[ui]"
    assert_output --partial "lang = zh-TW"
}

@test "config_show --json emits valid JSON" {
    _load_config
    config_set ui.lang zh-TW
    config_set install.install_target sudo
    run config_show --json
    assert_success
    echo "${output}" | jq -e '.ui.lang == "zh-TW"' > /dev/null
    echo "${output}" | jq -e '.install.install_target == "sudo"' > /dev/null
}

@test "config_show --json on empty config returns {}" {
    _load_config
    config_init
    run config_show --json
    assert_success
    echo "${output}" | jq -e '. == {}' > /dev/null
}
